
package org.mlink.iwm.session.exthandler;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ExtHandler", targetNamespace = "http://exthandler.session.iwm.mlink.org/")
public interface ExtHandler {


    /**
     * 
     * @param textToExtHandler
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestInfo", targetNamespace = "http://exthandler.session.iwm.mlink.org/", className = "org.mlink.iwm.session.exthandler.RequestInfo")
    @ResponseWrapper(localName = "requestInfoResponse", targetNamespace = "http://exthandler.session.iwm.mlink.org/", className = "org.mlink.iwm.session.exthandler.RequestInfoResponse")
    public String requestInfo(
        @WebParam(name = "textToExtHandler", targetNamespace = "")
        String textToExtHandler);

}
