/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "ActionLabel": { "text": "Item", "view": "DC.Text" },
    "actionslabel": { "text": "Actions:", "view": "DC.Text" },
    "ActionsList": { "allowsEmptySelection": true, "dataArray": ["Item 1", "Item 2", "Item 3"], "dataSourceName": "ActionsListDataSource", "labelElementId": "ActionLabel", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 3, "selectionEnabled": true, "useDataSource": true, "view": "DC.List" },
    "back_button": { "initialHeight": 30, "initialWidth": 50, "leftImageWidth": 16, "rightImageWidth": 5, "text": "Back", "view": "DC.PushButton" },
    "browser": { "clearSelectionOnBack": true, "view": "DC.Browser" },
    "closeJobButton": { "initialHeight": 30, "initialWidth": 140, "leftImageWidth": 5, "onclick": "closeJob", "rightImageWidth": 5, "text": "Close This Job", "view": "DC.PushButton" },
    "desc": { "text": "desc", "view": "DC.Text" },
    "header": { "rootTitle": "Mobile Worker", "view": "DC.Header" },
    "infoButton": { "initialHeight": 30, "initialWidth": 280, "leftImageWidth": 5, "onclick": "reqInfo", "rightImageWidth": 16, "text": "See Requester Info", "view": "DC.PushButton" },
    "jobDesc": { "text": "desc", "view": "DC.Text" },
    "jobid": { "text": "id", "view": "DC.Text" },
    "jobLoc": { "text": "Locator: Not.Really.Here", "view": "DC.Text" },
    "jobNote": { "text": "Note:", "view": "DC.Text" },
    "JobsList": { "allowsEmptySelection": true, "dataArray": ["Item 1", "Item 2", "Item 3"], "dataSourceName": "JobsListDataSource", "labelElementId": "desc", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 3, "selectionEnabled": true, "useDataSource": true, "view": "DC.List" },
    "jobTyp": { "text": "Type:", "view": "DC.Text" },
    "label": { "text": "Item", "view": "DC.Text" },
    "locator": { "text": "locator", "view": "DC.Text" },
    "LoginButton": { "initialHeight": 30, "initialWidth": 60, "leftImageWidth": 5, "onclick": "Login", "rightImageWidth": 16, "text": "Login", "view": "DC.PushButton" },
    "numberOfJobs": { "text": "5", "view": "DC.Text" },
    "objTag": { "text": "Object:", "view": "DC.Text" },
    "ScheduleList": { "allowsEmptySelection": true, "dataArray": ["Item 1"], "dataSourceName": "ScheduleListDataSource", "labelElementId": "label", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 3, "selectionEnabled": true, "useDataSource": true, "view": "DC.List" },
    "stackLayout": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "task_desc": { "text": "desc", "view": "DC.Text" },
    "TasksLabel": { "text": "Tasks:", "view": "DC.Text" },
    "TasksList": { "allowsEmptySelection": true, "dataArray": ["Item 1", "Item 2", "Item 3"], "dataSourceName": "TasksListDataSource", "labelElementId": "task_desc", "listStyle": "List.ROUNDED_RECTANGLE", "sampleRows": 1, "selectionEnabled": true, "useDataSource": true, "view": "DC.List" },
    "text": { "text": "Username", "view": "DC.Text" },
    "text1": { "text": "Password", "view": "DC.Text" },
    "text2": { "text": "Time:", "view": "DC.Text" },
    "text3": { "text": "Description:", "view": "DC.Text" },
    "time": { "text": "Text", "view": "DC.Text" }
};

