package org.mlink.agent.model;
// Generated May 25, 2006 7:06:40 AM by Hibernate Tools 3.1.0.beta5


import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/**
 * JobSpec generated by hbm2java
 */
public class JobSpec implements java.io.Serializable {
    
	// Fields    
	private Long        id;
	private String      createdBy;
	private Timestamp   createdDate;
	private String      description;
	private Integer     estimatedTime;
	private TaskTypeRef typeRef;
	private Integer     numWorkers;
	private Integer     priority;
	private Integer     sequenceLevel;
	private Long        skillLevel;
	private Long        skillType;
	private SkillLevelRef skillLevelRef;
	private SkillTypeRef  skillTypeRef;
	private List<TaskView> tasks;

     // Constructors

    /** default constructor */
    public JobSpec() {tasks = new ArrayList<TaskView>();}

    /** full constructor */
    public JobSpec(List<TaskView> tasks) {this.tasks = tasks;}
    
   
    // Property accessors
    public Long          getId()           {return this.id;}
	public String        getCreatedBy()    {return createdBy;}
	public Timestamp     getCreatedDate()  {return createdDate;}
    public String        getDescription()  {return this.description;}
    public Integer       getEstimatedTime(){return this.estimatedTime;}
    public TaskTypeRef   getTypeRef()      {return this.typeRef;}
    public Integer       getNumWorkers()   {return this.numWorkers;}
    public Integer       getPriority()     {return this.priority;}	
    public Integer       getSequenceLevel(){return this.sequenceLevel;}
    public Long          getSkillLevel()   {return this.skillLevel;}
    public Long          getSkillType()    {return this.skillLevel;}
    public SkillLevelRef getSkillLevelRef(){return this.skillLevelRef;}
    public SkillTypeRef  getSkillTypeRef() {return this.skillTypeRef;}
    public List getTasks()                 {return this.tasks;}
    public List<TaskView> getTaskViews()   {return this.tasks;}
    
    public void setId(Long id)               {this.id = id;}
	public void setCreatedBy(String s)       {this.createdBy=s;}
	public void setCreatedDate(Timestamp t)  {this.createdDate=t;}
    public void setDescription(String s)     {this.description=s;}
    public void setEstimatedTime(Integer i)  {this.estimatedTime=i;}
    public void setTypeRef(TaskTypeRef tr)   {this.typeRef=tr;}
    public void setNumWorkers(Integer i)     {this.numWorkers=i;}
    public void setPriority(Integer i)       {this.priority=i;}
    public void setSequenceLevel(Integer i)  {this.sequenceLevel=i;}
    public void setSkillLevel(Long l)        {this.skillLevel=l;}
    public void setSkillType(Long l)         {this.skillType=l;}
    public void setSkillLevelRef(SkillLevelRef r){this.skillLevelRef=r;}
    public void setSkillTypeRef(SkillTypeRef r)  {this.skillTypeRef=r;}
    public void setTasks(List<TaskView> tasks){this.tasks = tasks;}
 
    /** 
     * Add the specified task to the set of tasks held by this JobSpec. This method will also
     * update the priority to the higher of the specified task or the JobSpec.
     * 
     * @param t the Task to add
     */
    public void addTask(TaskView t) {
    	if (tasks == null) tasks=new ArrayList<TaskView>();
    	if (tasks.contains(t)) return;
    	try {
    		int i = Integer.parseInt(t.getPriorityRef().getCode());
    		if (i > this.priority) {
    			this.priority = i;
    		}
    	} catch (Exception e) {
    		//continue
    	}
    	tasks.add(t);
    }
}


