//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.30 at 12:17:09 AM EDT 
//


package org.mlink.agent.xao;

/*
 * Java 5 features
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
 */

/**
 * <p>Java class for simResponse element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="simResponse">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="action">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="clone"/>
 *               &lt;enumeration value="delete"/>
 *               &lt;enumeration value="modify"/>
 *               &lt;enumeration value="rename"/>
 *               &lt;enumeration value="run"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="display" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="lastSimulation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="parent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="simid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="success"/>
 *               &lt;enumeration value="error"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "")
//@XmlRootElement(name = "simResponse")
public class SimResponse {

    //@XmlAttribute
    protected String action;
    //@XmlAttribute
    protected String display;
    //@XmlAttribute
    protected String lastSimulation;
    //@XmlAttribute
    protected String name;
    //@XmlAttribute
    protected String parent;
    //@XmlAttribute
    protected String simid;
    //@XmlAttribute
    protected String status;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the display property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplay() {
        return display;
    }

    /**
     * Sets the value of the display property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplay(String value) {
        this.display = value;
    }

    /**
     * Gets the value of the lastSimulation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastSimulation() {
        return lastSimulation;
    }

    /**
     * Sets the value of the lastSimulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastSimulation(String value) {
        this.lastSimulation = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the simid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimid() {
        return simid;
    }

    /**
     * Sets the value of the simid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimid(String value) {
        this.simid = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
